routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductoController;
//use CloudinaryLabs\CloudinaryLaravel\MediaAlly;//va en el modelo
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/producto', function () {
    return view('producto.index');
});

//Route::get('/producto/create',[ProductoController::class,'create']);

Route::resource('producto', ProductoController::class);
Route::get('/producto/ver',[ProductoController::class,'ver'])->name('producto.ver');

Route::get('upload', function () {
    return view('upload');
});
Route::post('upload', function (Request $request) {
    $uploadedFileUrl = Cloudinary::upload($request->file('imagen')->getRealPath(), [
        'folder' => 'Testting', //guardo IMG en la carpeta Tesstting, si esta carpeta no existe "lo crea"
    ])->getSecurePath();
    //dd($uploadedFileUrl);
});

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use CloudinaryLabs\CloudinaryLaravel\MediaAlly;//va en el modelo
class Producto extends Model
{
    use MediaAlly;
    protected $fillable = ['nombre', 'description','precio','stock','imagen','estado'];
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Producto;
use App\Models\Image;
//use CloudinaryLabs\CloudinaryLaravel\MediaAlly;//va en el modelo
use Cloudinary;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$productos = Producto::paginate(5)
        $productos = Producto::all();
        return view('producto.index', compact('productos'));
        //return view('layout.app', compact('productos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('producto.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $array_url = [];
        $producto = new Producto();
        $producto->nombre = $request->get('nombre');
        $producto->description = $request->get('description');
        $producto->precio = $request->get('precio');
        $producto->stock = $request->get('stock');
        $producto->estado = $request->get('estado');
        $cant = count($request->file('file'));
        for ($i=0; $i < $cant; $i++) {
            $uploadedFileUrl = Cloudinary::upload($request->file('file')[$i]->getRealPath())->getSecurePath();
            array_push($array_url, $uploadedFileUrl);
        }
        $producto->save();
        $id = $producto->id;
        for ($i=0; $i < count($array_url) ; $i++) { 
            $imagen = new Image();
            $imagen->url = $array_url[$i];
            $imagen->producto_id = $id;
            $imagen->estado = "ACTIVO";
            $imagen->save();
        }
        return redirect()->route('producto.index')->with('success','Producto creado correctamente.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $producto = Producto::findOrFail($id);
        $images = Image::where('producto_id', $id)->get();
        return view('producto.ver', compact('producto', 'images'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = Producto::findOrFail($id);
        return view('producto.edit', compact('producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nombre' => 'required',
        ]);
        $array_url = [];
        $producto = Producto::findOrFail($id);
        $producto->nombre = $request->get('nombre');
        $producto->description = $request->get('description');
        $producto->precio = $request->get('precio');
        $producto->stock = $request->get('stock');
        $producto->estado = $request->get('estado');
        $urlLast = $request->get('lastImage');
        if (!empty($request->file('imagenNueva'))) {
            $cant = count($request->file('imagenNueva'));
            // Eliminar imagenes anteriores de Cloudinary
            $images = Image::where('producto_id', $id)->get();
            if(!empty($images)) {
                for ($i=0; $i < count($images); $i++) { 
                    $a = explode("/", $images[$i]->url);
                    $aa = end($a);
                    $nom = explode(".", $aa);
                    $s= $nom[0];
                    Cloudinary::destroy($s);
                }
                // Eliminar registros anteriores de tabla Images
                for ($i=0; $i < count($images); $i++) { 
                    Image::findOrFail($images[$i]->id)->delete();
                }      
            }

            // Carga imagenes nuevas en array y cloudinary
            for ($i=0; $i < $cant; $i++) {
                $uploadedFileUrl = Cloudinary::upload($request->file('imagenNueva')[$i]->getRealPath())->getSecurePath();
                array_push($array_url, $uploadedFileUrl);
            }
            // Cargo imagenes en tabla Image
            for ($i=0; $i < count($array_url) ; $i++) { 
                $imagen = new Image();
                $imagen->url = $array_url[$i];
                $imagen->producto_id = $id;
                $imagen->estado = "ACTIVO";
                $imagen->save();
            }  
        }
        $producto->save();

        return redirect()->route('producto.index')->with('success', 'Contacto actualizado correctamente');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Eliminar imagenes anteriores de Cloudinary
        $images = Image::where('producto_id', $id)->get();
        if(!empty($images)) {
            for ($i=0; $i < count($images); $i++) { 
                $a = explode("/", $images[$i]->url);
                $aa = end($a);
                $nom = explode(".", $aa);
                $s= $nom[0];
                Cloudinary::destroy($s);
            }
            // Eliminar registros anteriores de tabla Images
            for ($i=0; $i < count($images); $i++) { 
                Image::findOrFail($images[$i]->id)->delete();
            } 
        }
        $producto = Producto::findOrFail($id)->delete();
        return back()->with("success", "Producto eliminado");
    }

}

resources/views/producto/create.blade.php
{{--<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>CRUD - MOGO</title>
        <!-- BOOTSTRAP 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

         <!-- Font Awesome CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    </head>
    <nav class="navbar navbar-dark bg-dark mb-4">
        <a href="/producto" class="navbar-brand">CRUD Mongo</a>
        <a href="{{ route('producto.show', 1) }}" class="navbar-brand">Landing</a>
    </nav>
    <body>--}}
@extends('layout.app')

@push('css')
    <style>
    </style>
@endpush
@section('content')
<div class="container">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Nuevo Producto</h1>
    </div>
    <div class="card mb-4" style="margin:auto;">
        <div class="card-body">
            <form class="" action="{{ url('/producto') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group py-2">
                    <input type="text" name="nombre" placeholder="Motorola X" class="form-control" required>
                </div>
                <div class="form-group py-2">
                    <textarea name="description" cols="80" class="form-control" placeholder="Celular Motorola X, Memoria 1TB..."></textarea>
                </div>
                <div class="form-group py-2">
                    <input type="text" name="precio" placeholder="S/. 1220" class="form-control">
                </div>
                <div class="form-group py-2">
                    <input type="text" name="stock" placeholder="8" class="form-control">
                </div>
                <div class="form-group py-2">
                    <input type="text" name="estado" placeholder="Disponible" class="form-control">
                </div>
                {{--<div class="form-group py-2">
                    <input type="file" name="imagen" placeholder="" class="form-control">
                </div>--}}
                <div class="form-group py-2">
                    <input type="file" name="file[]" multiple class="form-control">
                </div>
                <div class="form-group text-center py-4">
                    <button type="submit" class="btn btn-primary" style="width:300px;">Agregar</button>
                    <a href="{{ route('producto.index') }}" class="btn btn-outline-secondary" style="width:300px;">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection



{{--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>--}}

resources/views/producto/edit.blade.php
{{--<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>CRUD - MOGO</title>
        <!-- BOOTSTRAP 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

         <!-- Font Awesome CDN-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    </head>
    <nav class="navbar navbar-dark bg-dark mb-4">
        <a href="/producto" class="navbar-brand">CRUD Mongo</a>
        <a href="{{ route('producto.show', 1) }}" class="navbar-brand">Landing</a>
    </nav>
    <body>--}}
@extends('layout.app')

@push('css')
<style>
</style>
@endpush
@section('content')
<div class="container">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Editar producto</h1>
    </div>
    <div class="card mb-4">
        <div class="card-body">
            <h3 style="color:#011344;">EDITAR PRODUCTO</h3>
            <form class="" action="{{ route('producto.update', $producto) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <input type="hidden" name="lastImage" value="{{ old('', $producto->imagen) }}">
                <div class="form-group py-2">
                    <div class="form-group {{ $errors->has('nombre') ? ' has-error' : '' }}">
                        <strong><label style="color:#0C2054;">Nombre</label></strong>
                        <input type="text" name="nombre" value="{{ old('nombre', $producto->nombre) }}" class="form-control" placeholder="Ingrese el nombre" required />
                        @if ($errors->has('nombre'))
                            <span class="help-block">
                                <strong>{{ $errors->first('nombre') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group py-2 {{ $errors->has('description') ? ' has-error' : '' }}">
                        <strong><label style="color:#0C2054;">description</label></strong>
                        <input type="text" name="description" value="{{ old('description', $producto->description) }}" class="form-control" placeholder="Ingrese descripcion" required />
                        @if ($errors->has('description'))
                            <span class="help-block">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group py-2 {{ $errors->has('precio') ? ' has-error' : '' }}">
                        <strong><label style="color:#0C2054;">Precio</label></strong>
                        <input type="text" name="precio" value="{{ old('precio', $producto->precio) }}" class="form-control" placeholder="Ingrese el precio" required />
                        @if ($errors->has('precio'))
                            <span class="help-block">
                                <strong>{{ $errors->first('precio') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group py-2 {{ $errors->has('stock') ? ' has-error' : '' }}">
                        <strong><label style="color:#0C2054;">Stock</label></strong>
                        <input type="text" name="stock" value="{{ old('stock', $producto->stock) }}" class="form-control" placeholder="Ingrese el stock" required />
                        @if ($errors->has('stock'))
                            <span class="help-block">
                                <strong>{{ $errors->first('stock') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group py-2 {{ $errors->has('estado') ? ' has-error' : '' }}">
                        <strong><label style="color:#0C2054;">Estado</label></strong>
                        <input type="text" name="estado" value="{{ old('estado', $producto->estado) }}" class="form-control" placeholder="Ingrese el estado" required />
                        @if ($errors->has('estado'))
                            <span class="help-block">
                                <strong>{{ $errors->first('estado') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group py-2">
                        <input type="file" name="imagenNueva[]" multiple placeholder="" class="form-control">
                    </div>
                    <div class="panel-footer text-center py-4">
                        <input type="submit" class="btn btn-primary" value="Guardar" style="width:300px;" data-loading-text="Guardando..."/>
                        <a href="{{ route('producto.index') }}" class="btn btn-outline-secondary" style="width:300px;">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
</div>


@endsection

{{--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>--}}

resources/views/producto/index.blade.php
{{--<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>CRUD</title>
        <!-- BOOTSTRAP 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

         <!-- Font Awesome CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    </head>
    <nav class="navbar navbar-dark bg-dark mb-4">
        <a href="/producto" class="navbar-brand">CRUD Mongo</a>
        <a href="{{ route('producto.show', 1) }}" class="navbar-brand">Landing</a>
    </nav>
    <body>
--}}
@extends('layout.app')

@push('css')
    <style>
    </style>
@endpush
@section('content')
<div class="container">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Productos</h1>
        
      </div>
      <div>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Precio</th>
                    <th>Stock</th>
                    <th>Estado</th>
                    <th scope="col" style="text-align:center"><a href="{{ route('producto.create') }}" class="h3"><i class="fas fa-plus-square text-success"></i></a></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($productos as $producto)
                    <tr>
                        <td>{{ $producto->nombre }}</td>
                        <td>{{ $producto->description }}</td>
                        <td>{{ $producto->precio }}</td>
                        <td>{{ $producto->stock }}</td>
                        <td>{{ $producto->estado }}</td>
                        <td>
                            <a href="{{ route('producto.show', $producto) }}" class="mr-2 border-0"><i class="far fa-eye text-info"></i></a>
                            <a href="{{ route('producto.edit', $producto) }}" class="mr-2 border-0"><i class="fas fa-pencil-alt text-warning"></i></a>
                            <form action="{{ route('producto.destroy', $producto) }}" method="post" style="margin:0px;">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="mr-2 border-0" title="Eliminar"
                                    onclick="return confirm('¿Desea eliminar este registro?')">
                                    <i class="fas fa-trash-alt text-danger" aria-hidden="true"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
      </div>  
</div>
@endsection

{{--

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>
--}}

resources/views/producto/ver.blade.php
{{--<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>CRUD</title>
        <!-- BOOTSTRAP 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

         <!-- Font Awesome CDN-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    </head>
    <nav class="navbar navbar-dark bg-dark mb-4">
        <a href="/producto" class="navbar-brand">CRUD</a>
    </nav>
    <body>--}}
@extends('layout.app')

@push('css')
    <style>
    </style>
@endpush
@section('content')
    <div class="container">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Ver productos</h1>
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <div class="mb-3">
                    <label>Nombre</label>
                    <input type="text" name="nombre" value="{{ old('nombre', $producto->nombre) }}" class="form-control" placeholder="Ingrese el nombre" disabled />
                </div>
                <div class="form-group">
                    <label>description</label>
                    <input type="text" name="description" value="{{ old('description', $producto->description) }}" class="form-control" placeholder="Ingrese descripcion" disabled />
                </div>
                <div class="form-group">
                    <label>precio</label>
                    <input type="text" name="precio" value="{{ old('precio', $producto->precio) }}" class="form-control" placeholder="Ingrese el precio" disabled />
                </div>
                <div class="form-group">
                    <label>stock</label>
                    <input type="text" name="stock" value="{{ old('stock', $producto->stock) }}" class="form-control" placeholder="Ingrese el stock" disabled />
                </div>
                <div class="form-group">
                    <label>estado</label>
                    <input type="text" name="estado" value="{{ old('estado', $producto->estado) }}" class="form-control" placeholder="Ingrese el estado" disabled />
                </div>
                @if (!empty($images))
                    <div class="row py-4">
                        @foreach ($images as $image)
                        <div class="col-4" style="margin: auto;">
                            <img src="{{ old('', $image->url) }}" alt="" style="width: 200px;">   
                        </div>
                        @endforeach
                    </div>
                @endif
                <div class="panel-footer py-2">
                    <a href="{{ route('producto.index') }}" class="btn btn-primary" style="width:100px;">Atras</a>
                </div>
            </div>
        </div>
    </div>
    @endsection
    {{--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

--}}